### PR TITLE
Don't requite GET_ACCOUNTS on ICS+ devices

### LINKED ISSUE #14: GET_ACCOUNTS permission is not needed on ICS+
You can have `maxSdkVersion` on the permission

Source: http://stackoverflow.com/questions/18444227/get-accounts-permission-while-using-gcm-why-is-this-needed.

### PR DESCRIPTION
**Pull request by DanielNovak**
* Fixes #14

### CODE REVIEW

**Comment by adrien-aubel** [comment]
For some reason my application can't start properly with 1.3.0-SNAPSHOT when triggered by PACKAGE_REPLACED.
It creates a SecurityException when accessing the system accounts.
Any idea?

**Comment by DanielNovak** [comment]
Which version of Android and device do you test it on? Can you post the exception with stack trace?

**Comment by adrien-aubel** [comment]
Android 5.0, OnePlus One.
I have a variety of devices I can check later today.

**Comment by DanielNovak** [comment]
@adrien-aubel Have you found some time to debug this problem? Can you post a stacktrace? I can't replicate this issue.

**Pull request merged**
